name: Upload Mod to NexusMods

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true

jobs:
  upload-to-nexusmods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip mod files
        run: git archive --format=zip --output=OAAB_Saplings.zip HEAD
        
      - name: Upload mod to NexusMods
        id: upload
        uses: Nexus-Mods/upload-action@v1.0.0-beta.3
        with:
          api_key: ${{ secrets.NEXUSMODS_API_KEY }}
          file_group_id: ${{ vars.NEXUSMODS_FILE_GROUP_ID }}
          filename: OAAB_Saplings.zip
          display_name: OAAB Saplings
          description: Testing nexus github action
          version: ${{ github.event.release.tag_name || github.event.inputs.version }}
